### PR TITLE
Add dependency injection for the store. This fixes a bunch of potential issues.

### PR DESCRIPTION
**Pull request by chilloutman**
Please review.

### CODE REVIEW

**Comment by steffinchen** [comment]
Looks good, but could you please add some simple tests for the RobopatrolStoreProvider class? Coverage is currently a bit low...

**Comment by chilloutman** [comment]
Will do.

**Comment by chilloutman** [comment]
Tests added. 👍

**Comment by steffinchen** [comment]
Excellent 💯.  Merging

**Pull request merged**
