### PR TITLE
Close open database connection on shutdown.

### PR DESCRIPTION
**Pull request by chilloutman**

### CODE REVIEW

**Comment by DeeVeX** [comment]
After a `gradle build` and `docker-compose up`
Still getting:

``` Java
...
Caused by: org.mapdb.DBException$DataCorruption: Header checksum broken. Store was not closed correctly, or is corrupted
...
java.lang.IllegalStateException: Unable to perform operation: create on ch.zhaw.robopatrol.res.Schedule
...
```

**Comment by chilloutman** [comment]
Alright, I'm using the transactions feature now. This should fix the problem. Please test again.

**Comment by DeeVeX** [comment]
Still the same problem. sorry.

**Comment by DeeVeX** [comment]
beautiful.

**Pull request merged**
